
// Code generated by stanc v2.22.1
#include <stan/model/model_header.hpp>
namespace infer_empirical_F_model_namespace {

template <typename T, typename S>
std::vector<T> resize_to_match__(std::vector<T>& dst, const std::vector<S>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, -1>
resize_to_match__(Eigen::Matrix<T, -1, -1>& dst, const Eigen::Matrix<T, -1, -1>& src) {
  dst.resize(src.rows(), src.cols());
  return dst;
}

template <typename T>
Eigen::Matrix<T, 1, -1>
resize_to_match__(Eigen::Matrix<T, 1, -1>& dst, const Eigen::Matrix<T, 1, -1>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, 1>
resize_to_match__(Eigen::Matrix<T, -1, 1>& dst, const Eigen::Matrix<T, -1, 1>& src) {
  dst.resize(src.size());
  return dst;
}
std::vector<double> to_doubles__(std::initializer_list<double> x) {
  return x;
}

std::vector<stan::math::var> to_vars__(std::initializer_list<stan::math::var> x) {
  return x;
}

inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 7, column 2 to column 13)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 8, column 2 to column 12)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 24, column 2 to column 15)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 27, column 4 to column 41)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 28, column 24 to column 38)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 28, column 4 to column 38)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 29, column 4 to column 38)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 26, column 17 to line 30, column 3)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 26, column 2 to line 30, column 3)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 15, column 2 to column 49)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 20, column 2 to column 28)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 21, column 2 to column 28)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 2, column 2 to column 17)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 3, column 2 to column 29)",
                                                      " (in '/Users/gchure/Dropbox/git/presentations/talks/20200219_SKlab_group_meeting/code/infer_empirical_F.stan', line 4, column 2 to column 27)"};


class infer_empirical_F_model : public model_base_crtp<infer_empirical_F_model> {

 private:
  int pos__;
  int N;
  std::vector<int> complaints;
  Eigen::Matrix<double, -1, 1> traps;
 
 public:
  ~infer_empirical_F_model() { }
  
  std::string model_name() const { return "infer_empirical_F_model"; }
  
  infer_empirical_F_model(stan::io::var_context& context__,
                          unsigned int random_seed__ = 0,
                          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    typedef double local_scalar_t__;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "infer_empirical_F_model_namespace::infer_empirical_F_model";
    (void) function__;  // suppress unused var warning
    
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      
      current_statement__ = 13;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 14;
      validate_non_negative_index("complaints", "N", N);
      context__.validate_dims("data initialization","complaints","int",
          context__.to_vec(N));
      complaints = std::vector<int>(N, 0);
      
      current_statement__ = 14;
      assign(complaints, nil_index_list(), context__.vals_i("complaints"),
        "assigning variable complaints");
      current_statement__ = 15;
      validate_non_negative_index("traps", "N", N);
      context__.validate_dims("data initialization","traps","double",
          context__.to_vec(N));
      traps = Eigen::Matrix<double, -1, 1>(N);
      
      {
        std::vector<local_scalar_t__> traps_flat__;
        current_statement__ = 15;
        assign(traps_flat__, nil_index_list(), context__.vals_r("traps"),
          "assigning variable traps_flat__");
        current_statement__ = 15;
        pos__ = 1;
        current_statement__ = 15;
        for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 15;
          assign(traps, cons_list(index_uni(sym1__), nil_index_list()),
            traps_flat__[(pos__ - 1)], "assigning variable traps");
          current_statement__ = 15;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 13;
      current_statement__ = 13;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 14;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_greater_or_equal(function__, "complaints[sym1__]",
                               complaints[(sym1__ - 1)], 0);}
      current_statement__ = 15;
      current_statement__ = 15;
      check_greater_or_equal(function__, "traps", traps, 0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
               std::ostream* pstream__ = 0) const {
    typedef T__ local_scalar_t__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "infer_empirical_F_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    
    try {
      local_scalar_t__ alpha;
      
      current_statement__ = 1;
      alpha = in__.scalar();
      local_scalar_t__ beta;
      
      current_statement__ = 2;
      beta = in__.scalar();
      {
        current_statement__ = 10;
        lp_accum__.add(
          poisson_log_log<propto__>(complaints,
            add(alpha, multiply(beta, traps))));
        current_statement__ = 11;
        lp_accum__.add(normal_log<propto__>(beta, -0.25, 0.5));
        current_statement__ = 12;
        lp_accum__.add(normal_log<propto__>(alpha, stan::math::log(7), 1));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                   std::vector<int>& params_i__, std::vector<double>& vars__,
                   bool emit_transformed_parameters__ = true,
                   bool emit_generated_quantities__ = true,
                   std::ostream* pstream__ = 0) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "infer_empirical_F_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    
    try {
      double alpha;
      
      current_statement__ = 1;
      alpha = in__.scalar();
      double beta;
      
      current_statement__ = 2;
      beta = in__.scalar();
      vars__.push_back(alpha);
      vars__.push_back(beta);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      current_statement__ = 3;
      validate_non_negative_index("y_rep", "N", N);
      std::vector<int> y_rep;
      y_rep = std::vector<int>(N, 0);
      
      current_statement__ = 9;
      for (size_t n = 1; n <= N; ++n) {
        double eta_n;
        
        current_statement__ = 4;
        eta_n = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 4;
        eta_n = (alpha + (beta * traps[(n - 1)]));
        current_statement__ = 6;
        if (logical_gte(eta_n, 20.79)) {
          current_statement__ = 5;
          eta_n = 20.79;
        } 
        current_statement__ = 7;
        assign(y_rep, cons_list(index_uni(n), nil_index_list()),
          poisson_log_rng(eta_n, base_rng__), "assigning variable y_rep");}
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.push_back(y_rep[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  void transform_inits(const stan::io::var_context& context__,
                       std::vector<int>& params_i__,
                       std::vector<double>& vars__, std::ostream* pstream__) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      
      pos__ = 1;
      double alpha;
      
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      double beta;
      
      current_statement__ = 2;
      beta = context__.vals_r("beta")[(1 - 1)];
      vars__.push_back(alpha);
      vars__.push_back(beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  void get_param_names(std::vector<std::string>& names__) const {
    
    names__.resize(0);
    names__.push_back("alpha");
    names__.push_back("beta");
    names__.push_back("y_rep");
    } // get_param_names() 
    
  void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.resize(0);
    std::vector<size_t> dims__;
    dimss__.push_back(dims__);
    dims__.resize(0);
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(N);
    dimss__.push_back(dims__);
    dims__.resize(0);
    
    } // get_dims() 
    
  void constrained_param_names(std::vector<std::string>& param_names__,
                               bool emit_transformed_parameters__ = true,
                               bool emit_generated_quantities__ = true) const {
    
    param_names__.push_back(std::string() + "alpha");
    param_names__.push_back(std::string() + "beta");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  void unconstrained_param_names(std::vector<std::string>& param_names__,
                                 bool emit_transformed_parameters__ = true,
                                 bool emit_generated_quantities__ = true) const {
    
    param_names__.push_back(std::string() + "alpha");
    param_names__.push_back(std::string() + "beta");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.push_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}

typedef infer_empirical_F_model_namespace::infer_empirical_F_model stan_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


